# Generated by Django 4.2 on 2023-05-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelousers',
            old_name='avatar',
            new_name='avatar',
        ),
    ]
