# Generated by Django 4.2 on 2023-06-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
