# Generated by Django 4.2 on 2023-06-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_modelousers_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelousers',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
